### ISSUE TITLE
Many providers depend on `gotestfmt` in custom tests

### ISSUE THREAD

**Issue by iwahbe** [pulumi/ci-mgmt#1070]
Many providers invoke `gotestfmt` in `preTest` provider test blocks. They relied on `gotestfmt` being installed. Since https://github.com/pulumi/ci-mgmt/pull/1069 uninstalled `gotestfmt`, the workflow upgrades are now failing CI.

Example of a provider using `gotestfmt` in `.ci-mgmt.yaml`:

```yaml
actions:
  preTest:
    - name: make upstream
      run: |
        make upstream
    - name: Run provider tests
      run: |
        cd provider && go test -v -json -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
```

([src](https://github.com/pulumi/pulumi-newrelic/blob/99654e48b30cec4f84a06cb944e68eeeb71ff57f/.ci-mgmt.yaml#L10C1-L18C1))

It looks like this effects about 40 providers. You can see a list of failing workflow upgrades [here](https://github.com/search?q=org:pulumi+Update+GitHub+Actions+workflows.+is:open+AND+NOT+in:title+%22Bump+%22+NOT+in:title+%22%5BDOWNSTREAM+TEST%5D%22&type=pullrequests).
