### ISSUE TITLE
PR comment is null

### ISSUE THREAD

**Issue by jkodroff** [pulumi/ci-mgmt#125]
In the following PR, we triggered a run of the integration tests, but the link back to the actions run was apparently null: https://github.com/pulumi/pulumi-aws/pull/1792

Looks like the issue is that the step is called `var`, but is referenced as `vars`:

```yaml
    - id: var
      name: Create URL to the run output
      run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
    - name: Update with Result
      uses: peter-evans/create-or-update-comment@v1
      with:
        body: Please view the PR build - ${{ steps.vars.outputs.run-url }}
```
