### ISSUE TITLE
Auto-update provider pins

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#1474]
.ci-mgmt.yaml pins providers such as aws=6.32.0. This is needed because it affects example generation and examples are serialized into the schema which is checked into the repository, as well as into SDKs which are also checked into the repository.  The suggestion here is to automate keeping these updated via PRs:

```
provider: random
major-version: 4
makeTemplate: bridged
plugins:
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.16"
    kind: converter
  - name: aws
    version: "6.32.0"
  - name: azure
    version: "5.24.0"
team: ecosystem
license:
  ignore:
    - github.com/terraform-providers/terraform-provider-random/shim
pulumiConvert: 1

```

The automation would need to update e.g. plugins[name='aws'] version and call make generate_sdks and check in the result.
