### ISSUE TITLE
Add release verification to aws native provider

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/ci-mgmt#1593]
Our workflows for bridged and component providers have a step for downloading and running a test against a released provider SDK at the end of the release workflow. We just have to configure a test for each repo to run on release. (It can be a very basic test as the only goal is to check for existence and basic function of the released provider binary and SDK.)

[Example from azure](https://github.com/pulumi/pulumi-azure/blob/e5b09682da88d50359d932ba5bd5f5d22f05f648/.ci-mgmt.yaml#L55-L60):

```yaml
releaseVerification:
  nodejs: examples/topic
  python: examples/eventhub-py
  dotnet: examples/appservice-cs
  go: examples/network-go
```
