### ISSUE TITLE
Add CI check `actionlint` to check generated GitHub Actions workflows

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/ci-mgmt#344]

**Comment by danielrbradley** [comment]
Example implementation in Azure Native:

https://github.com/pulumi/pulumi-azure-native/blob/7b05175f2879eb3fb55426e4c8ba8033ccd0a56c/.github/workflows/acceptance-test.yml#L59-L66
```
  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Lint actions
        uses: reviewdog/action-actionlint@v1.36.0
```

Ideally this would be done before pushing out to each individual provider too though.
