### ISSUE TITLE
Improve cache keys for tests

### ISSUE THREAD

**Issue by t0yv0** [pulumi/ci-mgmt#527]
Looking at pulumi-aws job:

https://github.com/pulumi/pulumi-aws/actions/runs/5977210773/job/16217954911?pr=2714

This used 30 min of CI time to run 0.1s test.

The reason for this I think is compiling go dependencies.

Go is invoked like this:

```
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.goversion}}
        cache-dependency-path: |
            sdk/go.sum
```

The build records a cache hit, but key deps are still missing so that Go toolchain re-downloads and re-compiles them.

One fix would be to switch to a precise dependency path:

```
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.goversion}}
        cache-dependency-path: |
            examples/go.sum
```

The reason we moved away from precise paths before, is that a common pattern of PRs is to change something in upstream dependencies. At the time it seemed like even small churn in dependencies such as switching upstream version would result in a cache miss, so that prebuilt dependencies wouldn't be downloaded at all, invalidating *all* dependencies and taking a hit in PRs build time by rebuilding *all* dependencies.  

Going to precise dependencies can bring this problem back.

There might be some hybrid middle ground. It's possible to to play with https://github.com/actions/cache directly as opposed to using it bundled via setup-go, and see if a good set of keys can be designed that avoids the problem. For example, test workflows can have cache keys that are independent of build workflows, ensuring that there's no "stomping" where build workflows write to the cache a dependency set that's missing test dependencies, while also sharing the cache across test runs.
